import {selectName,num,sum,isOpen,nextTenth,monthKey,deadline,isCardLike,addDays} from './airtable.mjs';

export function transform(raw,today){
  const {liquidityRaw,cashflowRaw,batchesRaw,hokRaw,debtsRaw,budgetRaw,goalsRaw,decisionsRaw,syncRaw}=raw;
  const horizon14=addDays(today,14);
  const goals=goalsRaw.map(r=>({id:r.id,name:r.fields['אירוע / יעד']||'',type:selectName(r.fields['סוג']),date:r.fields['תאריך']||'',targetDate:r.fields['תאריך יעד']||'',impact:num(r.fields['סכום השפעה עד היעד']),monthlyAddition:num(r.fields['תוספת חודשית קבועה']),status:selectName(r.fields['סטטוס']),countsAsSuccess:Boolean(r.fields['נספר כהצלחה']),source:r.fields['מקור / אסמכתא']||'',notes:r.fields['הערות']||''}));
  const activeTarget=goals.filter(x=>x.type==='יעד תזרים'&&isOpen(x.status)&&!x.name.includes('בונצל')&&(!x.targetDate||x.targetDate>=today)).sort((a,b)=>(a.targetDate||'9999').localeCompare(b.targetDate||'9999'))[0]||null;
  const targetDate=activeTarget?.targetDate||nextTenth(today),targetYm=targetDate.slice(0,7),targetYear=targetDate.slice(0,4);

  const liquidity=liquidityRaw.map(r=>({id:r.id,name:r.fields['מקור נזילות']||'',type:selectName(r.fields['סוג']),balance:num(r.fields['יתרה בפועל']),facility:num(r.fields['מסגרת אשראי']),restricted:num(r.fields['כספים מיועדים / מוגבלים']),free:num(r.fields['יתרה חופשית']),headroom:num(r.fields['מרווח למסגרת']),status:selectName(r.fields['סטטוס']),verifiedAt:r.fields['עודכן ואומת']||'',notes:r.fields['הערות']||''}));
  const actualFreeLiquidity=sum(liquidity,x=>x.free),facilityHeadroom=sum(liquidity.filter(x=>x.facility>0),x=>x.headroom),operationalLiquidityWithinFacilities=sum(liquidity,x=>x.facility>0?x.headroom:x.free);

  const cashflow=cashflowRaw.map(r=>({id:r.id,description:r.fields['תיאור']||'',dataType:selectName(r.fields['סוג נתון']),direction:selectName(r.fields['כיוון']),amount:num(r.fields['סכום']),date:r.fields['תאריך']||'',status:selectName(r.fields['סטטוס']),source:r.fields['מקור מידע']||'',notes:r.fields['הערות']||'',account:selectName(r.fields['חשבון / קופה']),category:selectName(r.fields['קטגוריה']),affectsLiquidity:Boolean(r.fields['משפיע על נזילות']),forecastMonth:r.fields['חודש תחזית']||''}));
  const openCashflow=cashflow.filter(x=>x.affectsLiquidity&&isOpen(x.status));
  const horizonCashflow=openCashflow.filter(x=>x.date&&x.date<=horizon14),targetCashflow=openCashflow.filter(x=>x.date&&x.date<=targetDate);
  const targetOut=sum(targetCashflow.filter(x=>x.direction==='הוצאה'),x=>x.amount),targetInCommitted=sum(targetCashflow.filter(x=>x.direction==='הכנסה'&&x.dataType==='התחייבות קיימת'),x=>x.amount),targetInForecast=sum(targetCashflow.filter(x=>x.direction==='הכנסה'&&x.dataType==='תחזית'),x=>x.amount);

  const cardBatches=batchesRaw.map(r=>{const expectedDate=r.fields['תאריך זיכוי צפוי']||'',expectedMonth=r.fields['חודש זיכוי צפוי']||'',notes=r.fields['הערות']||'',deadlineFromNotes=deadline(notes,targetYear),mk=expectedDate?expectedDate.slice(0,7):monthKey(expectedMonth),status=selectName(r.fields['סטטוס']);let countsByTarget=false,timingBasis='';if(isOpen(status)){if(expectedDate){countsByTarget=expectedDate<=targetDate;timingBasis='תאריך זיכוי צפוי'}else if(deadlineFromNotes){countsByTarget=deadlineFromNotes<=targetDate;timingBasis='מועד מתועד בהערות'}else if(mk&&mk<targetYm){countsByTarget=true;timingBasis='חודש זיכוי מוקדם מחודש היעד'}else timingBasis='אין יום זיכוי מאומת בתוך חלון היעד'}return{id:r.id,name:r.fields['זיכוי']||'',expectedDate,expectedMonth,monthKey:mk,deadlineFromNotes,gross:num(r.fields['סכום ברוטו צפוי']),deductions:num(r.fields['עמלות וקיזוזים צפויים']),net:num(r.fields['סכום נטו צפוי']),status,bank:selectName(r.fields['בנק יעד']),actual:num(r.fields['סכום זיכוי בפועל']),actualDate:r.fields['תאריך זיכוי בפועל']||'',notes,countsByTarget,timingBasis}});
  const cardNetByTarget=sum(cardBatches.filter(x=>x.countsByTarget),x=>x.net||(x.gross-x.deductions));

  const pendingHok=hokRaw.map(r=>{const expectedChargeDate=r.fields['מועד חיוב צפוי']||'',immediateLiquidity=Boolean(r.fields['משפיע מיידית על נזילות']),method=r.fields['אמצעי גבייה']||'',route=selectName(r.fields['חשבון / מסלול']),status=selectName(r.fields['סטטוס']),amount=num(r.fields['סכום צפוי']),chargeYm=expectedChargeDate?expectedChargeDate.slice(0,7):monthKey(r.fields['חודש חיוב']||'');let cashByTarget=false,cashReason='';if(isOpen(status)&&expectedChargeDate&&expectedChargeDate<=targetDate){if(immediateLiquidity){cashByTarget=true;cashReason='משפיע מיידית על נזילות'}else if(isCardLike(method,route)&&chargeYm&&chargeYm<targetYm){cashByTarget=true;cashReason='חיוב אשראי לפני חודש היעד — תחזית זיכוי'}else cashReason='החיוב צפוי אך אין בסיס לזיכוי בבנק עד היעד'}return{id:r.id,donor:r.fields['תורם / הו״ק']||'',amount,chargeMonth:r.fields['חודש חיוב']||'',expectedChargeDate,chargeYm,method,status,immediateLiquidity,route,notes:r.fields['הערות']||'',cashByTarget,cashReason}});
  const hokPendingTarget=pendingHok.filter(x=>isOpen(x.status)&&x.expectedChargeDate&&x.expectedChargeDate<=targetDate),hokPendingAmount=sum(hokPendingTarget,x=>x.amount),hokCashByTarget=sum(hokPendingTarget.filter(x=>x.cashByTarget),x=>x.amount),hokImmediateAmount=sum(hokPendingTarget.filter(x=>x.immediateLiquidity&&x.cashByTarget),x=>x.amount),hokSettlementForecast=hokCashByTarget-hokImmediateAmount;

  const debts=debtsRaw.map(r=>({id:r.id,creditor:r.fields['נושה / התחייבות']||'',original:num(r.fields['סכום מקורי']),balance:num(r.fields['יתרה לתשלום']),dueDate:r.fields['מועד תשלום']||'',type:selectName(r.fields['סוג']),risk:selectName(r.fields['דירוג סיכון']),status:selectName(r.fields['סטטוס']),agreement:r.fields['הבטחת תשלום / הסדר']||'',counted:Boolean(r.fields['נספר בסיכום']),notes:r.fields['הערות']||''}));
  const openCountedDebts=debts.filter(x=>x.counted&&isOpen(x.status)),debtTotal=sum(openCountedDebts,x=>x.balance),criticalDebtTotal=sum(openCountedDebts.filter(x=>x.risk.startsWith('A')),x=>x.balance);
  const budget=budgetRaw.map(r=>({month:r.fields['חודש']||'',monthStart:r.fields['תחילת חודש']||'',structuralIncome:num(r.fields['סה״כ הכנסות מבניות']),structuralExpenses:num(r.fields['סה״כ הוצאות מבניות כולל שירות חוב']),structuralGap:num(r.fields['פער מבני חודשי']),operatingGapBeforeDebt:num(r.fields['פער תפעולי לפני שירות חוב']),status:selectName(r.fields['סטטוס שלמות'])})).sort((a,b)=>(a.monthStart||'9999').localeCompare(b.monthStart||'9999'));
  const successes=goals.filter(x=>x.countsAsSuccess&&(!activeTarget?.date||x.date>=activeTarget.date)&&(!activeTarget?.targetDate||!x.targetDate||x.targetDate===activeTarget.targetDate)),successImpact=sum(successes,x=>x.impact),structuralMonthlyWins=sum(successes,x=>x.monthlyAddition);
  const decisions=decisionsRaw.map(r=>({id:r.id,subject:r.fields['החלטה / נושא']||'',date:r.fields['תאריך החלטה']||'',area:selectName(r.fields['תחום']),policy:r.fields['כלל מדיניות חל']||'',recommendation:r.fields['המלצת החשב']||'',decision:r.fields['החלטה']||'',approver:r.fields['מאשר']||'',status:selectName(r.fields['סטטוס החלטה']),deviation:Boolean(r.fields['חריגה מהמדיניות']),risk:r.fields['סיכון']||''}));
  const sync=syncRaw.map(r=>({process:r.fields['תהליך']||'',lastSuccess:r.fields['ריצה אחרונה מוצלחת']||'',status:selectName(r.fields['סטטוס']),anomalies:num(r.fields['חריגות פתוחות']),notes:r.fields['הערות ריצה']||''}));

  const committedWithoutFacilities=actualFreeLiquidity+cardNetByTarget+targetInCommitted,committedWithinFacilities=operationalLiquidityWithinFacilities+cardNetByTarget+targetInCommitted,forecastAdds=hokCashByTarget+targetInForecast;
  const metrics={actualFreeLiquidity,facilityHeadroom,operationalLiquidityWithinFacilities,targetOut,targetInCommitted,targetInForecast,cardNetByTarget,hokPendingAmount,hokCashByTarget,hokImmediateAmount,hokSettlementForecast,conservativeGapWithoutFacilities:targetOut-committedWithoutFacilities,conservativeGapWithinFacilities:targetOut-committedWithinFacilities,forecastGapWithoutFacilities:targetOut-(committedWithoutFacilities+forecastAdds),forecastGapWithinFacilities:targetOut-(committedWithinFacilities+forecastAdds),debtTotal,criticalDebtTotal,successImpact,structuralMonthlyWins};
  return {connected:true,fetchedAt:new Date().toISOString(),localDate:today,horizon14,targetDate,metrics,liquidity,cashflow:horizonCashflow.sort((a,b)=>a.date.localeCompare(b.date)),targetCashflow:targetCashflow.sort((a,b)=>a.date.localeCompare(b.date)),cardBatches,pendingHok:pendingHok.sort((a,b)=>(a.expectedChargeDate||'9999').localeCompare(b.expectedChargeDate||'9999')),debts:openCountedDebts,budget,goals,activeTarget,successes,decisions,sync};
}
